--Boobytrap
local s,id=GetID()
function s.initial_effect(c)
    aux.AddSkillProcedure(c,id,false,nil,nil)
    local e1=Effect.CreateEffect(c)
    e1:SetProperty(EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
    e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
    e1:SetCode(EVENT_STARTUP)
    e1:SetCountLimit(1)
    e1:SetRange(0x5f)
    e1:SetLabel(0)
    e1:SetOperation(s.flipop)
    c:RegisterEffect(e1)
end
s.listed_names={43906884}
function s.flipop(e,tp,eg,ep,ev,re,r,rp)
    Duel.Hint(HINT_SKILL_FLIP,tp,id|(1<<32))
	Duel.Hint(HINT_CARD,tp,id)
	local c=e:GetHandler()
    local e2=Effect.CreateEffect(c)
    e2:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
    e2:SetCode(EVENT_PHASE+PHASE_DRAW)
    e2:SetCountLimit(1)
    e2:SetOperation(s.skillop)
    e2:SetReset(RESET_PHASE|PHASE_END)
    Duel.RegisterEffect(e2,tp)
end
function s.skillop(e,tp,eg,ep,ev,re,r,rp)
    Duel.Hint(HINT_CARD,tp,id)
    Duel.Damage(1-tp,1000,REASON_EFFECT)
    local bt1=Duel.CreateToken(tp, 43906884)
    local bt2=Duel.CreateToken(tp, 43906884)
    local g=Group.FromCards(bt1, bt2)
    Duel.SendtoHand(g, tp, REASON_EFFECT)
    Duel.ConfirmCards(1-tp, g)
    Duel.ShuffleHand(tp)
end